version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        # managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mysql
            migrations: true
            host: mysql-db
            port: 3306
            user: root
            password: prisma
  mysql-db:
    image: mysql:5.7
    restart: always
    command: --innodb_use_native_aio=0
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - ./data/db:/var/lib/mysql
volumes:
  mysql: